<h1>Entre em contato conosco</h1>
<form method="post" action="<?php echo $this->url('estoque',['action'=>'contato']);?>">
    <div class="form-group">
        <label>Nome:</label>
        <input type="text" name="nome" class="form-control" />
    </div>
    <div class="form-group">
        <label>Email:</label>
        <input type="email" name="email" class="form-control" />
    </div>
    <div class="form-group">
        <label>Mensagem:</label>
        <textarea name="mensagem" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <input type="submit" value="Enviar" class="btn btn-primary" />
    </div>
</form>
