<h1>Editar Produto</h1>
<form method="post" action="<?php echo $this->url('estoque_param', ['action'=> 'editar', 'id' => $produto->getId()]);?>">
    <div class="form-group">
        <label>Nome</label>
        <input type="hidden" name="id" value="<?php echo $produto->getId();?>" />
        <input type="text" name="nome" class="form-control" value="<?php echo $produto->getNome();?>" />
    </div>

    <div class="form-group">
        <label>Preço</label>
        <input type="number" name="preco" class="form-control" value="<?php echo $produto->getPreco();?>" />
    </div>

    <div class="form-group">
        <label>Descrição</label>
        <textarea name="descricao" class="form-control"><?php echo $produto->getDescricao();?></textarea>
    </div>
    
    <div class="form-group">
        <input type="submit" value="Salvar Alterações" class="btn btn-primary"/>
    </div>
</form>
