<h1>Listagem de Produtos</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Categoria</td>
            <td>Preço</td>
            <td>Descrição</td>
            <td>Ações</td>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($produtos as $produto) {
            ?>
            <tr>
                <td><?php echo $produto->getNome(); ?></td>
                <td><?php echo $produto->getCategoria()->getDescricao(); ?></td>
                <td><?php echo $produto->getPreco(); ?></td>
                <td><?php echo $produto->getDescricao(); ?></td>
                <td>
                    <a href="<?php echo $this->url('estoque_param', ['action' => 'editar', 'id' => $produto->getId()]); ?>" class="btn btn-info">Editar</a>
                    <a href="<?php echo $this->url('estoque_param', ['action' => 'remover', 'id' => $produto->getId()]); ?>" class="btn btn-danger">Remover</a>
                </td>
            </tr>
            <?php
        }
        ?>
    </tbody>
</table>
<?php echo $this->paginationHelper($produtos, $qtdePorPagina, 'index'); ?>

