<h1>Login</h1>
<form action="<?php echo $this->url('estoque', ['controller' => 'usuario', 'action' => 'login']);?>" method="post">
    <div class="form-group">
        <label for="login">Login:</label>
        <input type="text" id="login" name="login" class="form-control" />
    </div>
    
    <div class="form-group">
        <label for="senha">Senha:</label>
        <input type="password" id="senha" name="senha" class="form-control" />
    </div>
    
    <div class="form-group">
        <input type="submit" value="Acessar" class="btn btn-primary" />
    </div>
</form>