<div class="col-md-12">
  <h1>Gerenciamento de Partida</h1>
  <h3><?php echo $objPartidaParticipantes[0]->getPartida()->getCampeonato()->getTitulo(); ?></h3>
</div>
<div class="col-md-12">
  <div class="col-md-2 ph0">
    <div class="form-group">
      <label>Data:</label>
      <?php echo $objPartidaParticipantes[0]->getPartida()->getData(); ?>
    </div>
  </div>
  <div class="col-md-12 ph0">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>PARTICIPANTE</th>
          <th>TAXA</th>
          <th>POSICAO</th>
          <th>AÇÃO</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($objPartidaParticipantes as $objParticipante): ?>
          <tr id=<?php echo $objParticipante->getIdPartidaUsuario(); ?>>
            <td width="60%"><?php echo $objParticipante->getParticipante()->getUsuario()->getNome(); ?></td>
            <td width="10%">
              <?php if ($objParticipante->getPago() == 0) { ?>
                <a href="#" class="btn btn-danger">PAGAR</a>
              <?php } else { ?>
                <a href="#" class="btn btn-success">PAGO</a>
              <?php } ?>
            </td>
            <td width="10%"><?php echo $objParticipante->getPosicao(); ?></td>
            <td width="20%">
              <?php if ($objParticipante->getPosicao() <= 0) { ?>
                <a href="#" class="btn btn-warning">PERDEDOR</a>
              <?php } else{ ?>
                <a href="#" class="btn btn-primary">CORRIGIR</a>
              <?php } ?>
            </td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
  <div class="col-md-12 ph0">
    <div class="form-group">
      <a href="<?php echo $this->url('partida_campeonato', ['idCampeonato' => $objPartidaParticipantes[0]->getPartida()->getCampeonato()->getIdCampeonato()]); ?>" class="btn btn-default">Voltar</a>
    </div>
  </div>
</div>