<div class="col-md-12">
    <h3>Nova Partida</h3>
</div>
<div class="col-md-12">
    <?php echo $this->form()->openTag($formPartida); ?>
    <div class="col-md-12 ph0">
        <div class="form-group">
            <label>Campeonato</label>
            <?php
            echo $this->formSelect($formPartida->get('campeonato'));
            echo $this->formElementErrors()->render($formPartida->get('campeonato'));
            ?>
        </div>
    </div>
    <div class="col-md-12 ph0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>PARTICIPANTE</th>
                    <th>AÇÃO</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>FELIPE</td>
                    <td><button name="btnEliminado" id="btnEliminado" class="btn btn-danger" value="ELIMINADO" /></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="col-md-12 ph0">
        <div class="form-group">
            <a href="<?php echo $this->url('listagem', ['controller' => 'partida']); ?>" class="btn btn-info">Voltar</a>
            <?php
            echo $this->formRow($formPartida->get('csrf'));
            echo $this->formInput($formPartida->get('btn_submit'));
            ?>
        </div>
    </div>
    <?php echo $this->form()->closeTag($formPartida); ?>
</div>