<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SysPoker')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
//            ->prependStylesheet($this->basePath() . '/css/style.css')S
            ->prependStylesheet($this->basePath() . '/js/jquery-ui-1.12.0/jquery-ui.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery-ui-1.12.0/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>
        <style>
            body {
                padding-top: 40px;
                padding-bottom: 40px;
                background-color: #eee;
            }

            .form-signin {
                max-width: 330px;
                padding: 15px;
                margin: 0 auto;
            }
            .form-signin .form-signin-heading,
            .form-signin .checkbox {
                margin-bottom: 10px;
            }
            .form-signin .checkbox {
                font-weight: normal;
            }
            .form-signin .form-control {
                position: relative;
                height: auto;
                -webkit-box-sizing: border-box;
                -moz-box-sizing: border-box;
                box-sizing: border-box;
                padding: 10px;
                font-size: 16px;
            }
            .form-signin .form-control:focus {
                z-index: 2;
            }
            .form-signin input[type="email"] {
                margin-bottom: -1px;
                border-bottom-right-radius: 0;
                border-bottom-left-radius: 0;
            }
            .form-signin input[type="password"] {
                margin-bottom: 10px;
                border-top-left-radius: 0;
                border-top-right-radius: 0;
            }
        </style>
    </head>
    <body>
        <div class="container">

            <form name="frmLogin" id="frmLogin" method="post" action="<?php echo $this->url('login'); ?>" class="form-signin">
                <h2 class="form-signin-heading"><?php echo $this->translate('Please sign in'); ?></h2>
                <label for="inputEmail" class="sr-only"><?php echo $this->translate('Email address or mobile number'); ?></label>
                <input type="email" name="username" id="username" class="form-control" placeholder="<?php echo $this->translate('Email address or mobile number'); ?>" required autofocus>
                <label for="inputPassword" class="sr-only"><?php echo $this->translate('Password'); ?></label>
                <input type="password" name="password" id="password" class="form-control" placeholder="<?php echo $this->translate('Password'); ?>" required>
                <button class="btn btn-lg btn-primary btn-block" type="submit"><?php echo $this->translate('Sign in'); ?></button>
            </form>
            <?php echo $this->flashHelper(); ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
