<div class="col-md-12">
    <h1>Remover Usuário/Participante</h1>
    <form method="post" action="<?php echo $this->url('padrao', ['controller' => 'usuario', 'action' => 'remove', 'id' => $objUsuario->getIdUsuario()]); ?>">
        <div class="form-group">
            <input type="hidden" name="id_usuario" value="<?php echo $objUsuario->getIdUsuario(); ?>" />
            <p class="alert alert-danger">Deseja realmente remover o usuário "<strong><?php echo $objUsuario->getNome(); ?></strong>" ?</p>
        </div>
        <div class="form-group">
            <input type="submit" value="Sim" class="btn btn-danger" />
            <a href="<?php echo $this->url('listagem', ['controller' => 'usuario']); ?>" class="btn btn-primary">Não</a>
        </div>
    </form>
</div>